services:
  admin-api:
    build: .
    container_name: admin-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    # 关键修改：引入外部的环境变量文件
    env_file:
      - .env # 指定环境变量文件的路径
    # 你也可以同时使用 `environment` 来覆盖或添加个别变量
    # environment:
    #   - LOG_LEVEL=debug
    networks:
      - admin-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"   # 对外暴露 HTTP 端口
      - "443:443" # 对外暴露 HTTPS 端口（如果你后续配置 SSL）
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # 挂载自定义的 Nginx 配置
      - ./ssl:/etc/nginx/ssl # 挂载 SSL 证书目录（后续配置 HTTPS 时使用）
    depends_on:
      - admin-api # 确保 node-app 服务先启动
    networks:
      - admin-network
  # ... nginx 配置保持不变
networks:
  admin-network:
    name: "admin-network"